In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer 
df=pd.read_csv("p:\\excel\\new12.csv")
df1=df.iloc[:,1:3]
print(df1)
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
imp.fit(df1)
print(imp.transform(df1))

   temperature  windspeed
0         23.0        8.0
1         27.0        9.0
2         28.0        NaN
3          NaN        7.0
4          NaN        NaN
5         31.0        2.0
6         34.0        5.0
[[23.   8. ]
 [27.   9. ]
 [28.   6.2]
 [28.6  7. ]
 [28.6  6.2]
 [31.   2. ]
 [34.   5. ]]

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv("p:\\excel\\new12.csv")
df.iloc[:,1].fillna(df.iloc[:,1].mean(),inplace=True)
df.iloc[:,2].fillna(df.iloc[:,2].mean(),inplace=True)
df

        day  temperature  windspeed     event
0  01-01-17         23.0        8.0      Rain
1  02-01-17         27.0        9.0     Sunny
2  03-01-17         28.0        6.2      Snow
3  04-01-17         28.6        7.0  no event
4  05-01-17         28.6        6.2      Rain
5  06-01-17         31.0        2.0     Sunny
6  07-01-17         34.0        5.0  no event

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv("p:\\excel\\new12.csv")
df['temperature'].fillna(df['temperature'].mean(),inplace=True)
df['windspeed'].fillna(df['windspeed'].mean(),inplace=True)
df

        day  temperature  windspeed     event
0  01-01-17         23.0        8.0      Rain
1  02-01-17         27.0        9.0     Sunny
2  03-01-17         28.0        6.2      Snow
3  04-01-17         28.6        7.0  no event
4  05-01-17         28.6        6.2      Rain
5  06-01-17         31.0        2.0     Sunny
6  07-01-17         34.0        5.0  no event